In [86]:
import pandas as pd

df = pd.read_csv("../data/goodreads_library_cleaned_descriptions.csv")

In [87]:
df["Description"].isna().sum()

np.int64(152)

# Data cleaning

In [88]:
# Enforce string type and fill NaNs with empty strings
df['Description'] = df['Description'].astype(str).fillna("")

In [89]:
# Strip leading/trailing whitespace
df['Description'] = df['Description'].str.strip()

In [90]:
df[["Title", "Author", "Description"]].head(20)

,Title,Author,Description
0,For Whom the Bell Tolls,Ernest Hemingway,"In 1937 Ernest Hemingway traveled to Spain to cover the civil war there for the North American Newspaper Alliance. Three years later he completed the greatest novel to emerge from “the good fight,” For Whom the Bell Tolls. The story of Robert Jordan, a young American in the International Brigades attached to an antifascist guerilla unit in the mountains of Spain, it tells of loyalty and courage, love and defeat, and the tragic death of an ideal. In his portrayal of Jordan's love for the beautiful Maria and his superb account of El Sordo's last stand, in his brilliant travesty of La Pasionaria and his unwillingness to believe in blind faith, Hemingway surpasses his achievement in The Sun Also Rises and A Farewell to Arms to create a work at once rare and beautiful, strong and brutal, compassionate, moving, and wise. “If the function of a writer is to reveal reality,” Maxwell Perkins wrote to Hemingway after reading the manuscript, “no one ever so completely performed it.” Greater in power, broader in scope, and more intensely emotional than any of the author's previous works, it stands as one of the best war novels of all time."
1,The Adventures of Tom Sawyer,Mark Twain,The classic adventure story of boyhood escapades on the shores of the Mississippi chronicles the exploits of the mischievous Tom Sawyer and his friends. Reissue.
2,The Fountainhead,Ayn Rand,"This centennial edition of ""The Fountainhead,"" celebrating the controversial and enduring legacy of its author, features an afterword by Rand's literary executor, Leonard Peikoff, offering some of Ayn Rand's personal notes on the development of her masterwork, and a Reader's Guide to her writings and philosophy."
3,To Have and Have Not,Ernest Hemingway,nan
4,Hello Beautiful,Ann Napolitano,nan
5,Do Androids Dream of Electric Sheep?,Philip K. Dick,"A masterpiece ahead of its time, a prescient rendering of a dark future, and the inspiration for the blockbuster film Blade Runner By 2021, the World War has killed millions, driving entire species into extinction and sending mankind off-planet. Those who remain covet any living creature, and for people who can’t afford one, companies built incredibly realistic simulacra: horses, birds, cats, sheep. They’ve even built humans. Immigrants to Mars receive androids so sophisticated they are indistinguishable from true men or women. Fearful of the havoc these artificial humans can wreak, the government bans them from Earth. Driven into hiding, unauthorized androids live among human beings, undetected. Rick Deckard, an officially sanctioned bounty hunter, is commissioned to find rogue androids and “retire” them. But when cornered, androids fight back—with lethal force. Praise for Philip K. Dick “The most consistently brilliant science fiction writer in the world.”—John Brunner “A kind of pulp-fiction Kafka, a prophet.”—The New York Times “[Philip K. Dick] sees all the sparkling—and terrifying—possibilities . . . that other authors shy away from.”—Rolling Stone"
6,The Vanishing Half,Brit Bennett,"#1 NEW YORK TIMES BESTSELLER ONE OF BARACK OBAMA'S FAVORITE BOOKS OF THE YEAR NAMED A BEST BOOK OF 2020 BY THE NEW YORK TIMES • THE WASHINGTON POST • NPR • PEOPLE • TIME MAGAZINE • VANITY FAIR • GLAMOUR New York Times Readers Pick: 100 Best Books of the 21st Century 2021 WOMEN'S PRIZE FINALIST “Bennett’s tone and style recalls James Baldwin and Jacqueline Woodson, but it’s especially reminiscent of Toni Morrison’s 1970 debut novel, The Bluest Eye.” —Kiley Reid, Wall Street Journal “A story of absolute, universal timelessness . . . For any era, it's an accomplished, affecting novel. For this moment, it’s piercing, subtly wending its way toward questions about who we are and who we want to be….” – Entertainment Weekly From The New York Times-bestselling author of The Mothers, a stunning new novel about twin sisters, inseparable as children, who ultimately choose to live in two very different worlds, one black and one white. The Vignes twin sisters will always be identical. But after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything: their families, their communities, their racial identities. Many years later, one sister lives with her black daughter in the same southern town she once tried to escape. The other secretly passes for white, and her white husband knows nothing of her past. Still, even separated by so many miles and just as many lies, the fates of the twins remain intertwined. What will happen to the next generation, when their own daughters' storylines intersect? Weaving together multiple strands and generations of this family, from the Deep South to California, from the 1950s to the 1990s, Brit Bennett produces a story that is at once a riveting, emotional family story and a brilliant exploration of the American history of passing. Looking well beyond issues of race, The Vanishing Half considers the lasting influence of the past as it shapes a person's decisions, desires, and expectations, and explores some of the multiple reasons and realms in which people sometimes feel pulled to live as something other than their origins. As with her New York Times-bestselling debut The Mothers, Brit Bennett offers an engrossing page-turner about family and relationships that is immersive and provocative, compassionate and wise."
7,All the Light We Cannot See,Anthony Doerr,"An imaginative and intricate novel inspired by the horrors of World War II and written in short, elegant chapters that explore human nature and the contradictory power of technology."
8,The Collected Stories,Amy Hempel,Publisher description
9,Where the Crawdads Sing,Delia Owens,"NOW A MAJOR MOTION PICTURE—The #1 New York Times bestselling worldwide sensation with more than 18 million copies sold, hailed by The New York Times Book Review as “a painfully beautiful first novel that is at once a murder mystery, a coming-of-age narrative and a celebration of nature.” New York Times Readers Pick: 100 Best Books of the 21st Century For years, rumors of the “Marsh Girl” have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl. But Kya is not what they say. Sensitive and intelligent, she has survived for years alone in the marsh that she calls home, finding friends in the gulls and lessons in the sand. Then the time comes when she yearns to be touched and loved. When two young men from town become intrigued by her wild beauty, Kya opens herself to a new life—until the unthinkable happens. Where the Crawdads Sing is at once an exquisite ode to the natural world, a heartbreaking coming-of-age story, and a surprising tale of possible murder. Owens reminds us that we are forever shaped by the children we once were, and that we are all subject to the beautiful and violent secrets that nature keeps."
10,Fahrenheit 451,Ray Bradbury,nan
11,The Catcher in the Rye,J.D. Salinger,"J.D. Salinger's classic of adolescent angst is now available for the first time in trade paperback. Holden Caulfield, knowing he is to be expelled from school, decides to leave early. He spends three days in New York City and tells the story of what he did and suffered there."
12,The Call of the Wild,Jack London,nan
13,Breakfast at Tiffany’s and Three Stories,Truman Capote,nan
14,"The Adventures of Huckleberry Finn (Adventures of Tom and Huck, #2)",Mark Twain,"A feisty young boy fakes his own death to escape his abusive father and heads off down the Mississippi River with his newfound friend Jim, a runaway slave."
15,Tender Is the Night,F. Scott Fitzgerald,nan
16,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"In a future North America, where the rulers of Panem maintain control through an annual televised survival competition pitting young people from each of the twelve districts against one another, sixteen-year-old Katniss's skills are put to the test when she voluntarily takes her younger sister's place."
17,I'm Glad My Mom Died,Jennette McCurdy,"* #1 NEW YORK TIMES BESTSELLER * #1 INTERNATIONAL BESTSELLER * MORE THAN 3 MILLION COPIES SOLD! A heartbreaking and hilarious memoir by iCarly and Sam & Cat star Jennette McCurdy about her struggles as a former child actor—including eating disorders, addiction, and a complicated relationship with her overbearing mother—and how she retook control of her life. Jennette McCurdy was six years old when she had her first acting audition. Her mother’s dream was for her only daughter to become a star, and Jennette would do anything to make her mother happy. So she went along with what Mom called “calorie restriction,” eating little and weighing herself five times a day. She endured extensive at-home makeovers while Mom chided, “Your eyelashes are invisible, okay? You think Dakota Fanning doesn’t tint hers?” She was even showered by Mom until age sixteen while sharing her diaries, email, and all her income. In I’m Glad My Mom Died, Jennette recounts all this in unflinching detail—just as she chronicles what happens when the dream finally comes true. Cast in a new Nickelodeon series called iCarly, she is thrust into fame. Though Mom is ecstatic, emailing fan club moderators and getting on a first-name basis with the paparazzi (“Hi Gale!”), Jennette is riddled with anxiety, shame, and self-loathing, which manifest into eating disorders, addiction, and a series of unhealthy relationships. These issues only get worse when, soon after taking the lead in the iCarly spinoff Sam & Cat alongside Ariana Grande, her mother dies of cancer. Finally, after discovering therapy and quitting acting, Jennette embarks on recovery and decides for the first time in her life what she really wants. Told with refreshing candor and dark humor, I’m Glad My Mom Died is an inspiring story of resilience, independence, and the joy of shampooing your own hair."
18,Journal 1970-1986,Andrei Tarkovsky,"""Tarkovsky for me is the greatest,"" wrote Ingmar Bergman. Andrey Tarkovsky only made seven films, but all are celebrated for its striking visual images, quietly patient dramatic structures, and visionary symbolism. Time within Time is both a diary and a notebook, maintained by Tarkovsky from 1970 until his death. Intense and intimate, it offers reflections on Dostoyevsky, Tolstoy, Hermann Hesse, Thomas Mann, and others. He writes movingly of his family, especially his father, Arseniy Tarkovsky, whose poems appear in his films. He records haunting dreams in detail and speaks of the state of society and the future of art, noting significant world events and purely personal dramas along with fascinating accounts of his own filmmaking. Rounding out this volume are Tarkovsky's plans and notes for his stage version of Hamlet; a detailed proposal for a film adaptation of Dostoyevsky's The Idiot; and a glimpse of the more public Tarkovsky answering questions put to him by interviewers."
19,Born a Crime: Stories from a South African Childhood,Trevor Noah,"The compelling, inspiring, and comically sublime New York Times bestseller about one man’s coming-of-age, set during the twilight of apartheid and the tumultuous days of freedom that followed. Trevor Noah’s unlikely path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth. Trevor was born to a white Swiss father and a black Xhosa mother at a time when such a union was punishable by five years in prison. Living proof of his parents’ indiscretion, Trevor was kept mostly indoors for the earliest years of his life, bound by the extreme and often absurd measures his mother took to hide him from a government that could, at any moment, steal him away. Finally liberated by the end of South Africa’s tyrannical white rule, Trevor and his mother set forth on a grand adventure, living openly and freely and embracing the opportunities won by a centuries-long struggle. Born a Crime is the story of a mischievous young boy who grows into a restless young man as he struggles to find himself in a world where he was never supposed to exist. It is also the story of that young man’s relationship with his fearless, rebellious, and fervently religious mother—his teammate, a woman determined to save her son from the cycle of poverty, violence, and abuse that would ultimately threaten her own life. The eighteen personal essays collected here are by turns hilarious, dramatic, and deeply affecting. Whether subsisting on caterpillars for dinner during hard times, being thrown from a moving car during an attempted kidnapping, or just trying to survive the life-and-death pitfalls of dating in high school, Trevor illuminates his curious world with an incisive wit and unflinching honesty. His stories weave together to form a moving and searingly funny portrait of a boy making his way through a damaged world in a dangerous time, armed only with a keen sense of humor and a mother’s unconventional, unconditional love."

In [91]:
# Lowercase all text
df['Description'] = df['Description'].str.lower()

In [92]:
# Replace repeated whitespace with single space
df['Description'] = df['Description'].str.replace(r'\s+', ' ', regex=True)

In [93]:
df[["Title", "Author", "Description"]].head(20)

,Title,Author,Description
0,For Whom the Bell Tolls,Ernest Hemingway,"in 1937 ernest hemingway traveled to spain to cover the civil war there for the north american newspaper alliance. three years later he completed the greatest novel to emerge from “the good fight,” for whom the bell tolls. the story of robert jordan, a young american in the international brigades attached to an antifascist guerilla unit in the mountains of spain, it tells of loyalty and courage, love and defeat, and the tragic death of an ideal. in his portrayal of jordan's love for the beautiful maria and his superb account of el sordo's last stand, in his brilliant travesty of la pasionaria and his unwillingness to believe in blind faith, hemingway surpasses his achievement in the sun also rises and a farewell to arms to create a work at once rare and beautiful, strong and brutal, compassionate, moving, and wise. “if the function of a writer is to reveal reality,” maxwell perkins wrote to hemingway after reading the manuscript, “no one ever so completely performed it.” greater in power, broader in scope, and more intensely emotional than any of the author's previous works, it stands as one of the best war novels of all time."
1,The Adventures of Tom Sawyer,Mark Twain,the classic adventure story of boyhood escapades on the shores of the mississippi chronicles the exploits of the mischievous tom sawyer and his friends. reissue.
2,The Fountainhead,Ayn Rand,"this centennial edition of ""the fountainhead,"" celebrating the controversial and enduring legacy of its author, features an afterword by rand's literary executor, leonard peikoff, offering some of ayn rand's personal notes on the development of her masterwork, and a reader's guide to her writings and philosophy."
3,To Have and Have Not,Ernest Hemingway,nan
4,Hello Beautiful,Ann Napolitano,nan
5,Do Androids Dream of Electric Sheep?,Philip K. Dick,"a masterpiece ahead of its time, a prescient rendering of a dark future, and the inspiration for the blockbuster film blade runner by 2021, the world war has killed millions, driving entire species into extinction and sending mankind off-planet. those who remain covet any living creature, and for people who can’t afford one, companies built incredibly realistic simulacra: horses, birds, cats, sheep. they’ve even built humans. immigrants to mars receive androids so sophisticated they are indistinguishable from true men or women. fearful of the havoc these artificial humans can wreak, the government bans them from earth. driven into hiding, unauthorized androids live among human beings, undetected. rick deckard, an officially sanctioned bounty hunter, is commissioned to find rogue androids and “retire” them. but when cornered, androids fight back—with lethal force. praise for philip k. dick “the most consistently brilliant science fiction writer in the world.”—john brunner “a kind of pulp-fiction kafka, a prophet.”—the new york times “[philip k. dick] sees all the sparkling—and terrifying—possibilities . . . that other authors shy away from.”—rolling stone"
6,The Vanishing Half,Brit Bennett,"#1 new york times bestseller one of barack obama's favorite books of the year named a best book of 2020 by the new york times • the washington post • npr • people • time magazine • vanity fair • glamour new york times readers pick: 100 best books of the 21st century 2021 women's prize finalist “bennett’s tone and style recalls james baldwin and jacqueline woodson, but it’s especially reminiscent of toni morrison’s 1970 debut novel, the bluest eye.” —kiley reid, wall street journal “a story of absolute, universal timelessness . . . for any era, it's an accomplished, affecting novel. for this moment, it’s piercing, subtly wending its way toward questions about who we are and who we want to be….” – entertainment weekly from the new york times-bestselling author of the mothers, a stunning new novel about twin sisters, inseparable as children, who ultimately choose to live in two very different worlds, one black and one white. the vignes twin sisters will always be identical. but after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything: their families, their communities, their racial identities. many years later, one sister lives with her black daughter in the same southern town she once tried to escape. the other secretly passes for white, and her white husband knows nothing of her past. still, even separated by so many miles and just as many lies, the fates of the twins remain intertwined. what will happen to the next generation, when their own daughters' storylines intersect? weaving together multiple strands and generations of this family, from the deep south to california, from the 1950s to the 1990s, brit bennett produces a story that is at once a riveting, emotional family story and a brilliant exploration of the american history of passing. looking well beyond issues of race, the vanishing half considers the lasting influence of the past as it shapes a person's decisions, desires, and expectations, and explores some of the multiple reasons and realms in which people sometimes feel pulled to live as something other than their origins. as with her new york times-bestselling debut the mothers, brit bennett offers an engrossing page-turner about family and relationships that is immersive and provocative, compassionate and wise."
7,All the Light We Cannot See,Anthony Doerr,"an imaginative and intricate novel inspired by the horrors of world war ii and written in short, elegant chapters that explore human nature and the contradictory power of technology."
8,The Collected Stories,Amy Hempel,publisher description
9,Where the Crawdads Sing,Delia Owens,"now a major motion picture—the #1 new york times bestselling worldwide sensation with more than 18 million copies sold, hailed by the new york times book review as “a painfully beautiful first novel that is at once a murder mystery, a coming-of-age narrative and a celebration of nature.” new york times readers pick: 100 best books of the 21st century for years, rumors of the “marsh girl” have haunted barkley cove, a quiet town on the north carolina coast. so in late 1969, when handsome chase andrews is found dead, the locals immediately suspect kya clark, the so-called marsh girl. but kya is not what they say. sensitive and intelligent, she has survived for years alone in the marsh that she calls home, finding friends in the gulls and lessons in the sand. then the time comes when she yearns to be touched and loved. when two young men from town become intrigued by her wild beauty, kya opens herself to a new life—until the unthinkable happens. where the crawdads sing is at once an exquisite ode to the natural world, a heartbreaking coming-of-age story, and a surprising tale of possible murder. owens reminds us that we are forever shaped by the children we once were, and that we are all subject to the beautiful and violent secrets that nature keeps."
10,Fahrenheit 451,Ray Bradbury,nan
11,The Catcher in the Rye,J.D. Salinger,"j.d. salinger's classic of adolescent angst is now available for the first time in trade paperback. holden caulfield, knowing he is to be expelled from school, decides to leave early. he spends three days in new york city and tells the story of what he did and suffered there."
12,The Call of the Wild,Jack London,nan
13,Breakfast at Tiffany’s and Three Stories,Truman Capote,nan
14,"The Adventures of Huckleberry Finn (Adventures of Tom and Huck, #2)",Mark Twain,"a feisty young boy fakes his own death to escape his abusive father and heads off down the mississippi river with his newfound friend jim, a runaway slave."
15,Tender Is the Night,F. Scott Fitzgerald,nan
16,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"in a future north america, where the rulers of panem maintain control through an annual televised survival competition pitting young people from each of the twelve districts against one another, sixteen-year-old katniss's skills are put to the test when she voluntarily takes her younger sister's place."
17,I'm Glad My Mom Died,Jennette McCurdy,"* #1 new york times bestseller * #1 international bestseller * more than 3 million copies sold! a heartbreaking and hilarious memoir by icarly and sam & cat star jennette mccurdy about her struggles as a former child actor—including eating disorders, addiction, and a complicated relationship with her overbearing mother—and how she retook control of her life. jennette mccurdy was six years old when she had her first acting audition. her mother’s dream was for her only daughter to become a star, and jennette would do anything to make her mother happy. so she went along with what mom called “calorie restriction,” eating little and weighing herself five times a day. she endured extensive at-home makeovers while mom chided, “your eyelashes are invisible, okay? you think dakota fanning doesn’t tint hers?” she was even showered by mom until age sixteen while sharing her diaries, email, and all her income. in i’m glad my mom died, jennette recounts all this in unflinching detail—just as she chronicles what happens when the dream finally comes true. cast in a new nickelodeon series called icarly, she is thrust into fame. though mom is ecstatic, emailing fan club moderators and getting on a first-name basis with the paparazzi (“hi gale!”), jennette is riddled with anxiety, shame, and self-loathing, which manifest into eating disorders, addiction, and a series of unhealthy relationships. these issues only get worse when, soon after taking the lead in the icarly spinoff sam & cat alongside ariana grande, her mother dies of cancer. finally, after discovering therapy and quitting acting, jennette embarks on recovery and decides for the first time in her life what she really wants. told with refreshing candor and dark humor, i’m glad my mom died is an inspiring story of resilience, independence, and the joy of shampooing your own hair."
18,Journal 1970-1986,Andrei Tarkovsky,"""tarkovsky for me is the greatest,"" wrote ingmar bergman. andrey tarkovsky only made seven films, but all are celebrated for its striking visual images, quietly patient dramatic structures, and visionary symbolism. time within time is both a diary and a notebook, maintained by tarkovsky from 1970 until his death. intense and intimate, it offers reflections on dostoyevsky, tolstoy, hermann hesse, thomas mann, and others. he writes movingly of his family, especially his father, arseniy tarkovsky, whose poems appear in his films. he records haunting dreams in detail and speaks of the state of society and the future of art, noting significant world events and purely personal dramas along with fascinating accounts of his own filmmaking. rounding out this volume are tarkovsky's plans and notes for his stage version of hamlet; a detailed proposal for a film adaptation of dostoyevsky's the idiot; and a glimpse of the more public tarkovsky answering questions put to him by interviewers."
19,Born a Crime: Stories from a South African Childhood,Trevor Noah,"the compelling, inspiring, and comically sublime new york times bestseller about one man’s coming-of-age, set during the twilight of apartheid and the tumultuous days of freedom that followed. trevor noah’s unlikely path from apartheid south africa to the desk of the daily show began with a criminal act: his birth. trevor was born to a white swiss father and a black xhosa mother at a time when such a union was punishable by five years in prison. living proof of his parents’ indiscretion, trevor was kept mostly indoors for the earliest years of his life, bound by the extreme and often absurd measures his mother took to hide him from a government that could, at any moment, steal him away. finally liberated by the end of south africa’s tyrannical white rule, trevor and his mother set forth on a grand adventure, living openly and freely and embracing the opportunities won by a centuries-long struggle. born a crime is the story of a mischievous young boy who grows into a restless young man as he struggles to find himself in a world where he was never supposed to exist. it is also the story of that young man’s relationship with his fearless, rebellious, and fervently religious mother—his teammate, a woman determined to save her son from the cycle of poverty, violence, and abuse that would ultimately threaten her own life. the eighteen personal essays collected here are by turns hilarious, dramatic, and deeply affecting. whether subsisting on caterpillars for dinner during hard times, being thrown from a moving car during an attempted kidnapping, or just trying to survive the life-and-death pitfalls of dating in high school, trevor illuminates his curious world with an incisive wit and unflinching honesty. his stories weave together to form a moving and searingly funny portrait of a boy making his way through a damaged world in a dangerous time, armed only with a keen sense of humor and a mother’s unconventional, unconditional love."

In [94]:
# Remove URLs
df['Description'] = df['Description'].str.replace(r'http\S+|www\.\S+', '', regex=True)

In [95]:
print(df['Description'].head(20))

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        in 1937 ernest hemingway traveled to spain to cover the civil war there for the north american newspaper alliance. three years later he completed the greatest novel to emerge from “the good fight,” for whom the bell tolls. the story of robert jordan, a young american in the international brigades attached to an antifascist guerilla unit in the mountains of spain, it tells of loyalty and courage, love and defeat, and the tragic death of an ideal. in his portrayal of jordan's love for the beautiful maria and his superb account of el sordo's last stand, in his brilliant travesty of la pasionaria and his unwillingness to believe in blind faith, hemingway surpasses his achievement in the sun also rises and a farewell to arms to create a work at once rare and beautiful, strong and brutal, compassionate, moving, and wise. “if the function of a writer is to reveal reality,” maxwell perkins wrote to hemingway after reading the manuscript, “no one ever so completely performed it.” greater in power, broader in scope, and more intensely emotional than any of the author's previous works, it stands as one of the best war novels of all time.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               the classic adventure story of boyhood escapades on the shores of the mississippi chronicles the exploits of the mischievous tom sawyer and his friends. reissue.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       this centennial edition of "the fountainhead," celebrating the controversial and enduring legacy of its author, features an afterword by rand's literary executor, leonard peikoff, offering some of ayn rand's personal notes on the development of her masterwork, and a reader's guide to her writings and philosophy.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             nan
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             nan
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            a masterpiece ahead of its time, a prescient rendering of a dark future, and the inspiration for the blockbuster film blade runner by 2021, the world war has killed millions, driving entire species into extinction and sending mankind off-planet. those who remain covet any living creature, and for people who can’t afford one, companies built incredibly realistic simulacra: horses, birds, cats, sheep. they’ve even built humans. immigrants to mars receive androids so sophisticated they are indistinguishable from true men or women. fearful of the havoc these artificial humans can wreak, the government bans them from earth. driven into hiding, unauthorized androids live among human beings, undetected. rick deckard, an officially sanctioned bounty hunter, is commissioned to find rogue androids and “retire” them. but when cornered, androids fight back—with lethal force. praise for philip k. dick “the most consistently brilliant science fiction writer in the world.”—john brunner “a kind of pulp-fiction kafka, a prophet.”—the new york times “[philip k. dick] sees all the sparkling—and terrifying—possibilities . . . that other authors shy away from.”—rolling stone
6     #1 new york times bestseller one of barack obama's favorite books of the year named a best book of 2020 by the new york times • the washington post • npr • people • time magazine • vanity fair • glamour new york times readers pick: 100 best books of the 21st century 2021 women's prize finalist “bennett’s tone and style recalls james baldwin and jacqueline woodson, but it’s especially reminiscent of toni morrison’s 1970 debut novel, the bluest eye.” —kiley reid, wall street journal “a story of absolute, universal timelessness . . . for any era, it's an accomplished, affecting novel. for this moment, it’s piercing, subtly wending its way toward questions about who we are and who we want to be….” – entertainment weekly from the new york times-bestselling author of the mothers, a stunning new novel about twin sisters, inseparable as children, who ultimately choose to live in two very different worlds, one black and one white. the vignes twin sisters will always be identical. but after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything: their families, their communities, their racial identities. many years later, one sister lives with her black daughter in the same southern town she once tried to escape. the other secretly passes for white, and her white husband knows nothing of her past. still, even separated by so many miles and just as many lies, the fates of the twins remain intertwined. what will happen to the next generation, when their own daughters' storylines intersect? weaving together multiple strands and generations of this family, from the deep south to california, from the 1950s to the 1990s, brit bennett produces a story that is at once a riveting, emotional family story and a brilliant exploration of the american history of passing. looking well beyond issues of race, the vanishing half considers the lasting influence of the past as it shapes a person's decisions, desires, and expectations, and explores some of the multiple reasons and realms in which people sometimes feel pulled to live as something other than their origins. as with her new york times-bestselling debut the mothers, brit bennett offers an engrossing page-turner about family and relationships that is immersive and provocative, compassionate and wise.
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          an imaginative and intricate novel inspired by the horrors of world war ii and written in short, elegant chapters that explore human nature and the contradictory power of technology.

In [96]:
# Replace repeated punctuation with single punctuation, excluding dots
df['Description'] = df['Description'].str.replace(r'([!?,;:-])\1+', r'\1', regex=True)

In [97]:
# Normalize multiple spaced dots to standard ellipsis
df['Description'] = df['Description'].str.replace(r'(\.\s){2,}\.', '...', regex=True)

In [104]:
 # Remove non-printable / OCR junk
df['Description'] = df['Description'].str.replace(r'[\x00-\x1f\x7f-\x9f]', '', regex=True)

In [105]:
# Strip again after replacements to clean up any leftover spaces
df['Description'] = df['Description'].str.strip()

In [106]:
print(df['Description'].head(20))

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      in 1937 ernest hemingway traveled to spain to cover the civil war there for the north american newspaper alliance. three years later he completed the greatest novel to emerge from “the good fight,” for whom the bell tolls. the story of robert jordan, a young american in the international brigades attached to an antifascist guerilla unit in the mountains of spain, it tells of loyalty and courage, love and defeat, and the tragic death of an ideal. in his portrayal of jordan's love for the beautiful maria and his superb account of el sordo's last stand, in his brilliant travesty of la pasionaria and his unwillingness to believe in blind faith, hemingway surpasses his achievement in the sun also rises and a farewell to arms to create a work at once rare and beautiful, strong and brutal, compassionate, moving, and wise. “if the function of a writer is to reveal reality,” maxwell perkins wrote to hemingway after reading the manuscript, “no one ever so completely performed it.” greater in power, broader in scope, and more intensely emotional than any of the author's previous works, it stands as one of the best war novels of all time.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             the classic adventure story of boyhood escapades on the shores of the mississippi chronicles the exploits of the mischievous tom sawyer and his friends. reissue.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     this centennial edition of "the fountainhead," celebrating the controversial and enduring legacy of its author, features an afterword by rand's literary executor, leonard peikoff, offering some of ayn rand's personal notes on the development of her masterwork, and a reader's guide to her writings and philosophy.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           NaN
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            a masterpiece ahead of its time, a prescient rendering of a dark future, and the inspiration for the blockbuster film blade runner by 2021, the world war has killed millions, driving entire species into extinction and sending mankind off-planet. those who remain covet any living creature, and for people who can’t afford one, companies built incredibly realistic simulacra: horses, birds, cats, sheep. they’ve even built humans. immigrants to mars receive androids so sophisticated they are indistinguishable from true men or women. fearful of the havoc these artificial humans can wreak, the government bans them from earth. driven into hiding, unauthorized androids live among human beings, undetected. rick deckard, an officially sanctioned bounty hunter, is commissioned to find rogue androids and “retire” them. but when cornered, androids fight back—with lethal force. praise for philip k. dick “the most consistently brilliant science fiction writer in the world.”—john brunner “a kind of pulp-fiction kafka, a prophet.”—the new york times “[philip k. dick] sees all the sparkling—and terrifying—possibilities ... that other authors shy away from.”—rolling stone
6     #1 new york times bestseller one of barack obama's favorite books of the year named a best book of 2020 by the new york times • the washington post • npr • people • time magazine • vanity fair • glamour new york times readers pick: 100 best books of the 21st century 2021 women's prize finalist “bennett’s tone and style recalls james baldwin and jacqueline woodson, but it’s especially reminiscent of toni morrison’s 1970 debut novel, the bluest eye.” —kiley reid, wall street journal “a story of absolute, universal timelessness ... for any era, it's an accomplished, affecting novel. for this moment, it’s piercing, subtly wending its way toward questions about who we are and who we want to be….” – entertainment weekly from the new york times-bestselling author of the mothers, a stunning new novel about twin sisters, inseparable as children, who ultimately choose to live in two very different worlds, one black and one white. the vignes twin sisters will always be identical. but after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything: their families, their communities, their racial identities. many years later, one sister lives with her black daughter in the same southern town she once tried to escape. the other secretly passes for white, and her white husband knows nothing of her past. still, even separated by so many miles and just as many lies, the fates of the twins remain intertwined. what will happen to the next generation, when their own daughters' storylines intersect? weaving together multiple strands and generations of this family, from the deep south to california, from the 1950s to the 1990s, brit bennett produces a story that is at once a riveting, emotional family story and a brilliant exploration of the american history of passing. looking well beyond issues of race, the vanishing half considers the lasting influence of the past as it shapes a person's decisions, desires, and expectations, and explores some of the multiple reasons and realms in which people sometimes feel pulled to live as something other than their origins. as with her new york times-bestselling debut the mothers, brit bennett offers an engrossing page-turner about family and relationships that is immersive and provocative, compassionate and wise.
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        an imaginative and intricate novel inspired by the horrors of world war ii and written in short, elegant chapters that explore human nature and the contradictory power of technology.

In [107]:
df.to_csv("../data/goodreads_library_descriptions_cleaned.csv", index=False)

In [108]:
df = pd.read_csv("../data/goodreads_library_descriptions_cleaned.csv")
df.head(20)

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Exclusive Shelf,My Rating,Average Rating,has_page_count,...,psychology,re-read,read,read-in-german,russian,sci-fi,science,to-read,travel,Description
0,For Whom the Bell Tolls,Ernest Hemingway,NaN,NaN,471.0,1940.0,read,0,3.99,1,...,0,0,0,0,0,0,0,0,0,"in 1937 ernest hemingway traveled to spain to cover the civil war there for the north american newspaper alliance. three years later he completed the greatest novel to emerge from “the good fight,” for whom the bell tolls. the story of robert jordan, a young american in the international brigades attached to an antifascist guerilla unit in the mountains of spain, it tells of loyalty and courage, love and defeat, and the tragic death of an ideal. in his portrayal of jordan's love for the beautiful maria and his superb account of el sordo's last stand, in his brilliant travesty of la pasionaria and his unwillingness to believe in blind faith, hemingway surpasses his achievement in the sun also rises and a farewell to arms to create a work at once rare and beautiful, strong and brutal, compassionate, moving, and wise. “if the function of a writer is to reveal reality,” maxwell perkins wrote to hemingway after reading the manuscript, “no one ever so completely performed it.” greater in power, broader in scope, and more intensely emotional than any of the author's previous works, it stands as one of the best war novels of all time."
1,The Adventures of Tom Sawyer,Mark Twain,NaN,9780143039563,244.0,1876.0,read,0,3.92,1,...,0,0,0,0,0,0,0,0,0,the classic adventure story of boyhood escapades on the shores of the mississippi chronicles the exploits of the mischievous tom sawyer and his friends. reissue.
2,The Fountainhead,Ayn Rand,NaN,NaN,704.0,1943.0,read,1,3.89,1,...,0,0,0,0,0,0,0,0,0,"this centennial edition of ""the fountainhead,"" celebrating the controversial and enduring legacy of its author, features an afterword by rand's literary executor, leonard peikoff, offering some of ayn rand's personal notes on the development of her masterwork, and a reader's guide to her writings and philosophy."
3,To Have and Have Not,Ernest Hemingway,NaN,NaN,176.0,1937.0,read,1,3.51,1,...,0,0,0,0,0,0,0,0,0,NaN
4,Hello Beautiful,Ann Napolitano,NaN,NaN,400.0,2023.0,read,2,4.13,1,...,0,0,0,0,0,0,0,0,0,NaN
5,Do Androids Dream of Electric Sheep?,Philip K. Dick,NaN,NaN,244.0,1968.0,read,2,4.09,1,...,0,0,0,0,0,0,0,0,0,"a masterpiece ahead of its time, a prescient rendering of a dark future, and the inspiration for the blockbuster film blade runner by 2021, the world war has killed millions, driving entire species into extinction and sending mankind off-planet. those who remain covet any living creature, and for people who can’t afford one, companies built incredibly realistic simulacra: horses, birds, cats, sheep. they’ve even built humans. immigrants to mars receive androids so sophisticated they are indistinguishable from true men or women. fearful of the havoc these artificial humans can wreak, the government bans them from earth. driven into hiding, unauthorized androids live among human beings, undetected. rick deckard, an officially sanctioned bounty hunter, is commissioned to find rogue androids and “retire” them. but when cornered, androids fight back—with lethal force. praise for philip k. dick “the most consistently brilliant science fiction writer in the world.”—john brunner “a kind of pulp-fiction kafka, a prophet.”—the new york times “[philip k. dick] sees all the sparkling—and terrifying—possibilities ... that other authors shy away from.”—rolling stone"
6,The Vanishing Half,Brit Bennett,0525536299,9780525536291,343.0,2020.0,read,3,4.12,1,...,0,0,0,0,0,0,0,0,0,"#1 new york times bestseller one of barack obama's favorite books of the year named a best book of 2020 by the new york times • the washington post • npr • people • time magazine • vanity fair • glamour new york times readers pick: 100 best books of the 21st century 2021 women's prize finalist “bennett’s tone and style recalls james baldwin and jacqueline woodson, but it’s especially reminiscent of toni morrison’s 1970 debut novel, the bluest eye.” —kiley reid, wall street journal “a story of absolute, universal timelessness ... for any era, it's an accomplished, affecting novel. for this moment, it’s piercing, subtly wending its way toward questions about who we are and who we want to be….” – entertainment weekly from the new york times-bestselling author of the mothers, a stunning new novel about twin sisters, inseparable as children, who ultimately choose to live in two very different worlds, one black and one white. the vignes twin sisters will always be identical. but after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything: their families, their communities, their racial identities. many years later, one sister lives with her black daughter in the same southern town she once tried to escape. the other secretly passes for white, and her white husband knows nothing of her past. still, even separated by so many miles and just as many lies, the fates of the twins remain intertwined. what will happen to the next generation, when their own daughters' storylines intersect? weaving together multiple strands and generations of this family, from the deep south to california, from the 1950s to the 1990s, brit bennett produces a story that is at once a riveting, emotional family story and a brilliant exploration of the american history of passing. looking well beyond issues of race, the vanishing half considers the lasting influence of the past as it shapes a person's decisions, desires, and expectations, and explores some of the multiple reasons and realms in which people sometimes feel pulled to live as something other than their origins. as with her new york times-bestselling debut the mothers, brit bennett offers an engrossing page-turner about family and relationships that is immersive and provocative, compassionate and wise."
7,All the Light We Cannot See,Anthony Doerr,1476746583,9781476746586,531.0,2014.0,read,3,4.31,1,...,0,0,0,0,0,0,0,0,0,"an imaginative and intricate novel inspired by the horrors of world war ii and written in short, elegant chapters that explore human nature and the contradictory power of technology."
8,The Collected Stories,Amy Hempel,0743289463,9780743289467,432.0,2006.0,read,3,4.25,1,...,0,0,0,0,0,0,0,0,0,publisher description
9,Where the Crawdads Sing,Delia Owens,0735219117,9780735219113,384.0,2018.0,read,4,4.37,1,...,0,0,0,0,0,0,0,0,0,"now a major motion picture—the #1 new york times bestselling worldwide sensation with more than 18 million copies sold, hailed by the new york times book review as “a painfully beautiful first novel that is at once a murder mystery, a coming-of-age narrative and a celebration of nature.” new york times readers pick: 100 best books of the 21st century for years, rumors of the “marsh girl” have haunted barkley cove, a quiet town on the north carolina coast. so in late 1969, when handsome chase andrews is found dead, the locals immediately suspect kya clark, the so-called marsh girl. but kya is not what they say. sensitive and intelligent, she has survived for years alone in the marsh that she calls home, finding friends in the gulls and lessons in the sand. then the time comes when she yearns to be touched and loved. when two young men from town become intrigued by her wild beauty, kya opens herself to a new life—until the unthinkable happens. where the crawdads sing is at once an exquisite ode to the natural world, a heartbreaking coming-of-age story, and a surprising tale of possible murder. owens reminds us that we are forever shaped by the children we once were, and that we are all subject to the beautiful and violent secrets that nature keeps."
10,Fahrenheit 451,Ray Bradbury,NaN,NaN,194.0,1953.0,read,4,3.97,1,...,0,0,0,0,0,0,0,0,0,NaN
11,The Catcher in the Rye,J.D. Salinger,0316769177,9780316769174,277.0,1951.0,read,4,3.80,1,...,0,0,0,0,0,0,0,0,0,"j.d. salinger's classic of adolescent angst is now available for the first time in trade paperback. holden caulfield, knowing he is to be expelled from school, decides to leave early. he spends three days in new york city and tells the story of what he did and suffered there."
12,The Call of the Wild,Jack London,NaN,NaN,172.0,1903.0,read,5,3.91,1,...,0,0,0,0,0,0,0,0,0,NaN
13,Breakfast at Tiffany’s and Three Stories,Truman Capote,NaN,NaN,142.0,1958.0,read,5,3.85,1,...,0,0,0,0,0,0,0,0,0,NaN
14,"The Adventures of Huckleberry Finn (Adventures of Tom and Huck, #2)",Mark Twain,0142437174,9780142437179,327.0,1885.0,read,5,3.83,1,...,0,0,0,0,0,0,0,0,0,"a feisty young boy fakes his own death to escape his abusive father and heads off down the mississippi river with his newfound friend jim, a runaway slave."
15,Tender Is the Night,F. Scott Fitzgerald,NaN,NaN,430.0,1934.0,read,4,3.77,1,...,0,0,0,0,0,0,0,0,0,NaN
16,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,0439023483,9780439023481,374.0,2008.0,read,3,4.35,1,...,0,0,0,1,0,0,0,0,0,"in a future north america, where the rulers of panem maintain control through an annual televised survival competition pitting young people from each of the twelve districts against one another, sixteen-year-old katniss's skills are put to the test when she voluntarily takes her younger sister's place."
17,I'm Glad My Mom Died,Jennette McCurdy,NaN,NaN,320.0,2022.0,read,0,4.44,1,...,0,0,0,0,0,0,0,0,0,"* #1 new york times bestseller * #1 international bestseller * more than 3 million copies sold! a heartbreaking and hilarious memoir by icarly and sam & cat star jennette mccurdy about her struggles as a former child actor—including eating disorders, addiction, and a complicated relationship with her overbearing mother—and how she retook control of her life. jennette mccurdy was six years old when she had her first acting audition. her mother’s dream was for her only daughter to become a star, and jennette would do anything to make her mother happy. so she went along with what mom called “calorie restriction,” eating little and weighing herself five times a day. she endured extensive at-home makeovers while mom chided, “your eyelashes are invisible, okay? you think dakota fanning doesn’t tint hers?” she was even showered by mom until age sixteen while sharing her diaries, email, and all her income. in i’m glad my mom died, jennette recounts all this in unflinching detail—just as she chronicles what happens when the dream finally comes true. cast in a new nickelodeon series called icarly, she is thrust into fame. though mom is ecstatic, emailing fan club moderators and getting on a first-name basis with the paparazzi (“hi gale!”), jennette is riddled with anxiety, shame, and self-loathing, which manifest into eating disorders, addiction, and a series of unhealthy relationships. these issues only get worse when, soon after taking the lead in the icarly spinoff sam & cat alongside ariana grande, her mother dies of cancer. finally, after discovering therapy and quitting acting, jennette embarks on recovery and decides for the first time in her life what she really wants. told with refreshing candor and dark humor, i’m glad my mom died is an inspiring story of resilience, independence, and the joy of shampooing your own hair."
18,Journal 1970-1986,Andrei Tarkovsky,NaN,NaN,NaN,1989.0,read,0,4.34,0,...,0,0,0,0,0,0,0,0,0,"""tarkovsky for me is the greatest,"" wrote ingmar bergman. andrey tarkovsky only made seven films, but all are celebrated for its striking visual images, quietly patient dramatic structures, and visionary symbolism. time within time is both a diary and a notebook, maintained by tarkovsky from 1970 until his death. intense and intimate, it offers reflections on dostoyevsky, tolstoy, hermann hesse, thomas mann, and others. he writes movingly of his family, especially his father, arseniy tarkovsky, whose poems appear in his films. he records haunting dreams in detail and speaks of the state of society and the future of art, noting significant world events and purely personal dramas along with fascinating accounts of his own filmmaking. rounding out this volume are tarkovsky's plans and notes for his stage version of hamlet; a detailed proposal for a film adaptation of dostoyevsky's the idiot; and a glimpse of the more public tarkovsky answering questions put to him by interviewers."
19,Born a Crime: Stories from a South African Childhood,Trevor Noah,0385689225,9780385689229,289.0,2016.0,read,2,4.49,1,...,0,0,0,0,0,0,0,0,0,"the compelling, inspiring, and comically sublime new york times bestseller about one man’s coming-of-age, set during the twilight of apartheid and the tumultuous days of freedom that followed. trevor noah’s unlikely path from apartheid south africa to the desk of the daily show began with a criminal act: his birth. trevor was born to a white swiss father and a black xhosa mother at a time when such a union was punishable by five years in prison. living proof of his parents’ indiscretion, trevor was kept mostly indoors for the earliest years of his life, bound by the extreme and often absurd measures his mother took to hide him from a government that could, at any moment, steal him away. finally liberated by the end of south africa’s tyrannical white rule, trevor and his mother set forth on a grand adventure, living openly and freely and embracing the opportunities won by a centuries-long struggle. born a crime is the story of a mischievous young boy who grows into a restless young man as he struggles to find himself in a world where he was never supposed to exist. it is also the story of that young man’s relationship with his fearless, rebellious, and fervently religious mother—his teammate, a woman determined to save her son from the cycle of poverty, violence, and abuse that would ultimately threaten her own life. the eighteen personal essays collected here are by turns hilarious, dramatic, and deeply affecting. whether subsisting on caterpillars for dinner during hard times, being thrown from a moving car during an attempted kidnapping, or just trying to survive the life-and-death pitfalls of dating in high school, trevor illuminates his curious world with an incisive wit and unflinching honesty. his stories weave together to form a moving and searingly funny portrait of a boy making his way through a damaged world in a dangerous time, armed only with a keen sense of humor and a mother’s unconventional, unconditional love."

In [103]:
df.isna().sum()

Title                          0
Author                         0
ISBN                         188
ISBN13                       182
Number of Pages                9
Original Publication Year     37
Exclusive Shelf                0
My Rating                      0
Average Rating                 0
has_page_count                 0
Bookshelves_clean              0
Tag_list                       0
american                       0
auto-biography                 0
children                       0
currently-reading              0
engineering                    0
ex-yu                          0
favorites                      0
feminism                       0
immigration                    0
indian                         0
latin-america                  0
lists                          0
own                            0
philosophy                     0
play                           0
poetry                         0
psychology                     0
re-read                        0
read                           0
read-in-german                 0
russian                        0
sci-fi                         0
science                        0
to-read                        0
travel                         0
Description                  152
dtype: int64