In [32]:
import pandas as pd

In [33]:
# Load Goodreads dataset
goodreads_df = pd.read_csv('../data/goodreads_library_export.csv')

In [34]:
goodreads_df.head()

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,...,Date Read,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,My Review,Spoiler,Private Notes,Read Count,Owned Copies
0,233411702,Planet Money: A Guide to the Economic Forces T...,Alex Mayyasi,"Mayyasi, Alex",Hosts of NPR's Planet Money,"=""1324078774""","=""9781324078777""",0,5.00,W. W. Norton & Company,...,NaN,2026/01/07,to-read,to-read (#629),to-read,NaN,NaN,NaN,0,0
1,228820257,The Calamity Club,Kathryn Stockett,"Stockett, Kathryn",NaN,"=""1954118813""","=""9781954118812""",0,4.39,Spiegel & Grau,...,NaN,2026/01/07,to-read,to-read (#628),to-read,NaN,NaN,NaN,0,0
2,231127042,Love by the Book,Jessica George,"George, Jessica",NaN,"=""1250282543""","=""9781250282545""",0,4.10,St. Martin's Press,...,NaN,2026/01/07,to-read,to-read (#627),to-read,NaN,NaN,NaN,0,0
3,235992421,Keeper of Lost Children,Sadeqa Johnson,"Johnson, Sadeqa",NaN,"=""1668069911""","=""9781668069912""",0,4.53,37 Ink,...,NaN,2026/01/07,to-read,to-read (#626),to-read,NaN,NaN,NaN,0,0
4,202468422,There Are Rivers in the Sky,Elif Shafak,"Shafak, Elif",NaN,"=""0593801717""","=""9780593801710""",0,4.36,Knopf,...,NaN,2026/01/07,to-read,to-read (#625),to-read,NaN,NaN,NaN,0,0

In [35]:
goodreads_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1132 entries, 0 to 1131
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Book Id                     1132 non-null   int64
 1   Title                       1132 non-null   object
 2   Author                      1132 non-null   object
 3   Author l-f                  1132 non-null   object
 4   Additional Authors          425 non-null    object
 5   ISBN                        1132 non-null   object
 6   ISBN13                      1132 non-null   object
 7   My Rating                   1132 non-null   int64
 8   Average Rating              1132 non-null   float64
 9   Publisher                   1108 non-null   object
 10  Binding                     1122 non-null   object
 11  Number of Pages             1123 non-null   float64
 12  Year Published              1119 non-null   float64
 13  Original Publication Year   1095 non-null   float64
 14  Date Read                   147 non-null    object
 15  Date Added                  1132 non-null   object
 16  Bookshelves                 875 non-null    object
 17  Bookshelves with positions  875 non-null    object
 18  Exclusive Shelf             1132 non-null   object
 19  My Review                   0 non-null      float64
 20  Spoiler                     0 non-null      float64
 21  Private Notes               0 non-null      float64
 22  Read Count                  1132 non-null   int64
 23  Owned Copies                1132 non-null   int64
dtypes: float64(7), int64(4), object(13)
memory usage: 212.4+ KB

In [36]:
goodreads_df.isna().sum()

Book Id                          0
Title                            0
Author                           0
Author l-f                       0
Additional Authors             707
ISBN                             0
ISBN13                           0
My Rating                        0
Average Rating                   0
Publisher                       24
Binding                         10
Number of Pages                  9
Year Published                  13
Original Publication Year       37
Date Read                      985
Date Added                       0
Bookshelves                    257
Bookshelves with positions     257
Exclusive Shelf                  0
My Review                     1132
Spoiler                       1132
Private Notes                 1132
Read Count                       0
Owned Copies                     0
dtype: int64

In [37]:
# Keep Title, Author, category, rating, and average rating columns
goodreads_df = goodreads_df[['Title', 'Author', 'ISBN', 'ISBN13', 'Number of Pages', 'Year Published', 'Original Publication Year', 'Bookshelves', 'Exclusive Shelf', 'My Rating', 'Average Rating']]

In [38]:
goodreads_df.head()

,Title,Author,ISBN,ISBN13,Number of Pages,Year Published,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating
0,Planet Money: A Guide to the Economic Forces T...,Alex Mayyasi,"=""1324078774""","=""9781324078777""",336.0,2026.0,NaN,to-read,to-read,0,5.00
1,The Calamity Club,Kathryn Stockett,"=""1954118813""","=""9781954118812""",656.0,2026.0,2026.0,to-read,to-read,0,4.39
2,Love by the Book,Jessica George,"=""1250282543""","=""9781250282545""",336.0,2026.0,2026.0,to-read,to-read,0,4.10
3,Keeper of Lost Children,Sadeqa Johnson,"=""1668069911""","=""9781668069912""",464.0,2026.0,2026.0,to-read,to-read,0,4.53
4,There Are Rivers in the Sky,Elif Shafak,"=""0593801717""","=""9780593801710""",446.0,2024.0,2024.0,to-read,to-read,0,4.36

In [39]:
goodreads_df.isna().sum()

Title                          0
Author                         0
ISBN                           0
ISBN13                         0
Number of Pages                9
Year Published                13
Original Publication Year     37
Bookshelves                  257
Exclusive Shelf                0
My Rating                      0
Average Rating                 0
dtype: int64

In [40]:
goodreads_df[goodreads_df['Number of Pages'].isna()]

,Title,Author,ISBN,ISBN13,Number of Pages,Year Published,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating
231,Ovo vrijeme sada,Semezdin Mehmedinović,"=""""","=""""",NaN,2020.0,NaN,"ex-yu, immigration, own",read,4,4.46
282,Sedam strahova (Seven Terrors),Selvedin Avdić,"=""""","=""""",NaN,2009.0,2009.0,to-read,to-read,0,3.56
483,The Black Swan: The Impact of the Highly Impro...,Nassim Nicholas Taleb,"=""""","=""""",NaN,2019.0,2007.0,"philosophy, psychology",read,2,3.96
581,I Know Why the Caged Bird Sings,Maya Angelou,"=""""","=""""",NaN,2011.0,1969.0,auto-biography,read,4,4.30
590,Journal 1970-1986,Andrei Tarkovsky,"=""""","=""""",NaN,NaN,1989.0,auto-biography,read,0,4.34
597,"Lelek Sebra, Kolajna",Tin Ujević,"=""""","=""""",NaN,NaN,NaN,"ex-yu, poetry",read,5,4.57
600,Igračka vjetrova,Tin Ujević,"=""""","=""""",NaN,NaN,NaN,"ex-yu, poetry",read,5,4.84
815,Doživljaji mačka Toše,Branko Ćopić,"=""""","=""""",NaN,NaN,1954.0,ex-yu,read,0,4.32
911,Nonlinear Control Systems (Communications and ...,Alberto Isidori,"=""3540199160""","=""9783540199168""",NaN,1995.0,1995.0,engineering,read,5,4.56

In [41]:
# Add has_page_count column
goodreads_df['Number of Pages'] = pd.to_numeric(goodreads_df['Number of Pages'], errors='coerce')   
goodreads_df['has_page_count'] = goodreads_df['Number of Pages'].notna().astype(int)

In [42]:
goodreads_df[goodreads_df['Number of Pages'].isna()]

,Title,Author,ISBN,ISBN13,Number of Pages,Year Published,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
231,Ovo vrijeme sada,Semezdin Mehmedinović,"=""""","=""""",NaN,2020.0,NaN,"ex-yu, immigration, own",read,4,4.46,0
282,Sedam strahova (Seven Terrors),Selvedin Avdić,"=""""","=""""",NaN,2009.0,2009.0,to-read,to-read,0,3.56,0
483,The Black Swan: The Impact of the Highly Impro...,Nassim Nicholas Taleb,"=""""","=""""",NaN,2019.0,2007.0,"philosophy, psychology",read,2,3.96,0
581,I Know Why the Caged Bird Sings,Maya Angelou,"=""""","=""""",NaN,2011.0,1969.0,auto-biography,read,4,4.30,0
590,Journal 1970-1986,Andrei Tarkovsky,"=""""","=""""",NaN,NaN,1989.0,auto-biography,read,0,4.34,0
597,"Lelek Sebra, Kolajna",Tin Ujević,"=""""","=""""",NaN,NaN,NaN,"ex-yu, poetry",read,5,4.57,0
600,Igračka vjetrova,Tin Ujević,"=""""","=""""",NaN,NaN,NaN,"ex-yu, poetry",read,5,4.84,0
815,Doživljaji mačka Toše,Branko Ćopić,"=""""","=""""",NaN,NaN,1954.0,ex-yu,read,0,4.32,0
911,Nonlinear Control Systems (Communications and ...,Alberto Isidori,"=""3540199160""","=""9783540199168""",NaN,1995.0,1995.0,engineering,read,5,4.56,0

In [43]:
goodreads_df[goodreads_df['Year Published'] != goodreads_df['Original Publication Year']]

,Title,Author,ISBN,ISBN13,Number of Pages,Year Published,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
0,Planet Money: A Guide to the Economic Forces T...,Alex Mayyasi,"=""1324078774""","=""9781324078777""",336.0,2026.0,NaN,to-read,to-read,0,5.00,1
6,The War of the End of the World,Mario Vargas Llosa,"=""0571139612""","=""9780571139613""",568.0,1986.0,1981.0,latin-america,read,2,4.25,1
7,A Dream of Red Mansions,Cao Xueqin,"=""7119006436""","=""9787119006437""",2549.0,2001.0,1791.0,to-read,to-read,0,4.53,1
8,Frostlines: A Journey Through Entangled Lives ...,Neil Shea,"=""0063138573""","=""9780063138575""",240.0,2025.0,NaN,to-read,to-read,0,4.16,1
9,A Long Game: Notes on Writing Fiction,Elizabeth McCracken,"=""006337529X""","=""9780063375291""",208.0,2025.0,NaN,to-read,to-read,0,4.32,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1127,Norwegian Wood,Haruki Murakami,"=""""","=""""",296.0,2000.0,1987.0,NaN,read,4,3.99,1
1128,The Overcoat,Nikolai Gogol,"=""1419176528""","=""9781419176524""",57.0,2004.0,1842.0,NaN,read,5,4.14,1
1129,The Name of the Rose,Umberto Eco,"=""0156001314""","=""9780156001311""",552.0,1994.0,1980.0,NaN,read,0,4.14,1
1130,War and Peace,Leo Tolstoy,"=""0192833987""","=""9780192833983""",1392.0,1998.0,1869.0,NaN,read,5,4.17,1
1131,Never Let Me Go,Kazuo Ishiguro,"=""1400078776""","=""9781400078776""",288.0,2010.0,2005.0,NaN,read,2,3.85,1

In [44]:
goodreads_df = goodreads_df.drop(columns=['Year Published'])

In [45]:
goodreads_df.columns

Index(['Title', 'Author', 'ISBN', 'ISBN13', 'Number of Pages',
       'Original Publication Year', 'Bookshelves', 'Exclusive Shelf',
       'My Rating', 'Average Rating', 'has_page_count'],
      dtype='object')

In [46]:
goodreads_df[goodreads_df['Original Publication Year'].isna()]

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
0,Planet Money: A Guide to the Economic Forces T...,Alex Mayyasi,"=""1324078774""","=""9781324078777""",336.0,NaN,to-read,to-read,0,5.00,1
8,Frostlines: A Journey Through Entangled Lives ...,Neil Shea,"=""0063138573""","=""9780063138575""",240.0,NaN,to-read,to-read,0,4.16,1
9,A Long Game: Notes on Writing Fiction,Elizabeth McCracken,"=""006337529X""","=""9780063375291""",208.0,NaN,to-read,to-read,0,4.32,1
19,The Gardener,Rabindranath Tagore,"=""1594568030""","=""9781594568039""",150.0,NaN,"poetry, indian",read,0,4.27,1
49,Skodelica kave / A Cup of Coffee,Ivan Cankar,"=""9612722536""","=""9789612722531""",43.0,NaN,"ex-yu, favorites",read,5,4.35,1
50,Goliath's Curse: The History and Future of Soc...,Luke Kemp,"=""0593321359""","=""9780593321355""",592.0,NaN,to-read,to-read,0,4.16,1
51,"The People's Project: Poems, Essays, and Art f...",Saeed Jones,"=""1668207028""","=""9781668207024""",128.0,NaN,to-read,to-read,0,4.26,1
57,Having It All: What Data Tells Us About Women'...,Corinne Low,"=""1250369517""","=""9781250369512""",272.0,NaN,to-read,to-read,0,3.92,1
60,Ring of Salt: A Memoir of Finding Home and Hop...,Betsy Cornwell,"=""166804529X""","=""9781668045299""",352.0,NaN,to-read,to-read,0,4.23,1
73,With Her Own Hands: Women Weaving Their Stories,Nicole Nehrig,"=""132407485X""","=""9781324074854""",288.0,NaN,to-read,to-read,0,4.11,1
114,The Montessori Baby: A Parent's Guide to Nurtu...,Simone Davies,"=""1523512407""","=""9781523512409""",288.0,NaN,children,read,4,3.92,1
149,Protocols: An Operating Manual for the Human Body,Andrew D. Huberman,"=""1668032147""","=""9781668032145""",512.0,NaN,to-read,to-read,0,3.89,1
165,Poetry from the Future: Why a Global Liberatio...,Srećko Horvat,"=""0241337321""","=""9780241337325""",176.0,NaN,to-read,to-read,0,4.01,1
166,Advancing Conversations: Srecko Horvat - Subve...,Srećko Horvat,"=""1785354965""","=""9781785354960""",96.0,NaN,to-read,to-read,0,4.14,1
192,Meho,Almin Kaplan,"=""9535201743""","=""9789535201748""",196.0,NaN,to-read,to-read,0,4.45,1
195,Poziv na crninu,Vojo Šindolić,"=""953707501X""","=""9789537075019""",249.0,NaN,to-read,to-read,0,4.75,1
206,Moj muž,Rumena Bužarovska,"=""9533047801""","=""9789533047805""",129.0,NaN,"ex-yu, own",read,5,4.01,1
231,Ovo vrijeme sada,Semezdin Mehmedinović,"=""""","=""""",NaN,NaN,"ex-yu, immigration, own",read,4,4.46,0
285,"It Wasn't Roaring, It Was Weeping: Interpretin...",Lisa-Jo Baker,"=""0525652868""","=""9780525652861""",272.0,NaN,to-read,to-read,0,4.42,1
363,Friendaholic: Confessions of a Friendship Addict,Elizabeth Day,"=""0008374902""","=""9780008374907""",416.0,NaN,to-read,to-read,0,3.73,1
405,Attachment Theory: A Guide to Strengthening th...,Thais Gibson,"=""1646115457""","=""9781646115457""",180.0,NaN,psychology,read,0,3.93,1
406,Python for Everybody: Exploring Data in Python 3,Charles Severance,"=""""","=""""",387.0,NaN,engineering,read,0,4.27,1
435,Classic Tales of Science Fiction & Fantasy,Jules Verne,"=""1626868018""","=""9781626868014""",1024.0,NaN,to-read,to-read,0,3.91,1
470,Running Smart: How Science Can Improve Your En...,Mariska van Sprundel,"=""0262542447""","=""9780262542449""",304.0,NaN,to-read,to-read,0,3.62,1
511,Life on Other Planets: A Memoir of Finding My ...,Aomawa Shields,"=""0593299183""","=""9780593299180""",352.0,NaN,to-read,to-read,0,4.11,1
524,Man and His Symbols: Approaching the Unconscious,C.G. Jung,"=""1879557177""","=""9781879557178""",3.0,NaN,"favorites, psychology",read,5,4.24,1
597,"Lelek Sebra, Kolajna",Tin Ujević,"=""""","=""""",NaN,NaN,"ex-yu, poetry",read,5,4.57,0
600,Igračka vjetrova,Tin Ujević,"=""""","=""""",NaN,NaN,"ex-yu, poetry",read,5,4.84,0
602,Brašno u venama,Igor Štiks,"=""9532667059""","=""9789532667059""",176.0,NaN,to-read,to-read,0,3.70,1
603,Rezalište,Igor Štiks,"=""9532668919""","=""9789532668919""",160.0,NaN,to-read,to-read,0,4.00,1
609,The PhD Career Coaching Guide: Job Search Stra...,Tina Persson,"=""""","=""""",123.0,NaN,to-read,to-read,0,4.00,1
681,Surrender Bono Autobiography 40 Songs By Bono ...,Bono,"=""9123556129""","=""9789123556120""",0.0,NaN,to-read,to-read,0,4.13,1
718,DBT Skills Training: Manual,Marsha M. Linehan,"=""1462516998""","=""9781462516995""",504.0,NaN,psychology,read,0,4.49,1
734,Maxims for Thinking Analytically: The wisdom o...,Dan Levy,"=""1735340898""","=""9781735340890""",211.0,NaN,science,read,0,3.93,1
735,The Great Mental Models Volume 3: Systems and ...,Rhiannon Beaubien,"=""1999449061""","=""9781999449063""",373.0,NaN,science,read,0,4.25,1
826,Most na Žepi,Ivo Andrić,"=""8673463785""","=""9788673463780""",54.0,NaN,ex-yu,read,0,4.17,1
1034,Jerusalem,Selma Lagerlöf,"=""1426489226""","=""9781426489228""",224.0,NaN,NaN,read,0,4.04,1

In [47]:
goodreads_df['Original Publication Year'].isna().sum()

np.int64(37)

In [48]:
goodreads_df[goodreads_df['Bookshelves'].isna()]

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
65,So Good They Can't Ignore You: Why Skills Trum...,Cal Newport,"=""1455509108""","=""9781455509102""",288.0,2012.0,NaN,read,3,4.07,1
102,Purple Hibiscus,Chimamanda Ngozi Adichie,"=""1616202416""","=""9781616202415""",336.0,2003.0,NaN,read,4,4.18,1
205,Mansfield Park,Jane Austen,"=""""","=""""",488.0,1814.0,NaN,read,0,3.86,1
222,The Lord of the Rings,J.R.R. Tolkien,"=""0618640150""","=""9780618640157""",1216.0,1959.0,NaN,read,0,4.54,1
234,Around the World in Eighty Days,Jules Verne,"=""014044906X""","=""9780140449068""",252.0,1872.0,NaN,read,0,3.95,1
...,...,...,...,...,...,...,...,...,...,...,...
1127,Norwegian Wood,Haruki Murakami,"=""""","=""""",296.0,1987.0,NaN,read,4,3.99,1
1128,The Overcoat,Nikolai Gogol,"=""1419176528""","=""9781419176524""",57.0,1842.0,NaN,read,5,4.14,1
1129,The Name of the Rose,Umberto Eco,"=""0156001314""","=""9780156001311""",552.0,1980.0,NaN,read,0,4.14,1
1130,War and Peace,Leo Tolstoy,"=""0192833987""","=""9780192833983""",1392.0,1869.0,NaN,read,5,4.17,1
1131,Never Let Me Go,Kazuo Ishiguro,"=""1400078776""","=""9781400078776""",288.0,2005.0,NaN,read,2,3.85,1

In [49]:
# Fill NaNs in 'Bookshelves' with 'read' if 'Exclusive Shelf' is 'read'
goodreads_df.loc[(goodreads_df['Bookshelves'].isna()) & (goodreads_df['Exclusive Shelf'] == 'read'), 'Bookshelves'] = 'read'

In [50]:
goodreads_df['Bookshelves'].isna().sum()

np.int64(0)

In [51]:
goodreads_df.isna().sum()

Title                         0
Author                        0
ISBN                          0
ISBN13                        0
Number of Pages               9
Original Publication Year    37
Bookshelves                   0
Exclusive Shelf               0
My Rating                     0
Average Rating                0
has_page_count                0
dtype: int64

In [52]:
goodreads_df.head()

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
0,Planet Money: A Guide to the Economic Forces T...,Alex Mayyasi,"=""1324078774""","=""9781324078777""",336.0,NaN,to-read,to-read,0,5.00,1
1,The Calamity Club,Kathryn Stockett,"=""1954118813""","=""9781954118812""",656.0,2026.0,to-read,to-read,0,4.39,1
2,Love by the Book,Jessica George,"=""1250282543""","=""9781250282545""",336.0,2026.0,to-read,to-read,0,4.10,1
3,Keeper of Lost Children,Sadeqa Johnson,"=""1668069911""","=""9781668069912""",464.0,2026.0,to-read,to-read,0,4.53,1
4,There Are Rivers in the Sky,Elif Shafak,"=""0593801717""","=""9780593801710""",446.0,2024.0,to-read,to-read,0,4.36,1

In [53]:
# Check for duplicate Title and Author combinations
dups = goodreads_df[goodreads_df.duplicated(subset=["Title", "Author"], keep=False)]
dups.sort_values(["Title", "Author"])

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
229,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,"=""""","=""""",306.0,2018.0,psychology,read,4,4.32,1
553,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,"=""""","=""""",319.0,2018.0,psychology,read,5,4.32,1
230,Hello Beautiful,Ann Napolitano,"=""""","=""""",400.0,2023.0,american,read,2,4.13,1
341,Hello Beautiful,Ann Napolitano,"=""""","=""""",594.0,2023.0,read,read,2,4.13,1

In [56]:
# Remove duplicates keeping the most complete entry
goodreads_df = (goodreads_df.sort_values(by=["Bookshelves", "My Rating"],
                                         ascending=[True, True]
                                         ).drop_duplicates(subset=["Title", "Author"], keep="first")
)

In [57]:
goodreads_df[goodreads_df.duplicated(subset=['Title', 'Author'])]

Empty DataFrame
Columns: [Title, Author, ISBN, ISBN13, Number of Pages, Original Publication Year, Bookshelves, Exclusive Shelf, My Rating, Average Rating, has_page_count]
Index: []

In [58]:
goodreads_df[goodreads_df['Author'] == 'James Clear']

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
229,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,"=""""","=""""",306.0,2018.0,psychology,read,4,4.32,1

In [59]:
goodreads_df[goodreads_df['Author'] == 'Ann Napolitano']

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
230,Hello Beautiful,Ann Napolitano,"=""""","=""""",400.0,2023.0,american,read,2,4.13,1

In [60]:
goodreads_df.head()

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
613,For Whom the Bell Tolls,Ernest Hemingway,"=""""","=""""",471.0,1940.0,american,read,0,3.99,1
619,The Adventures of Tom Sawyer,Mark Twain,"=""""","=""9780143039563""",244.0,1876.0,american,read,0,3.92,1
612,The Fountainhead,Ayn Rand,"=""""","=""""",704.0,1943.0,american,read,1,3.89,1
999,To Have and Have Not,Ernest Hemingway,"=""""","=""""",176.0,1937.0,american,read,1,3.51,1
230,Hello Beautiful,Ann Napolitano,"=""""","=""""",400.0,2023.0,american,read,2,4.13,1

In [66]:
# Clean ISBN and ISBN13 columns
goodreads_df["ISBN"] = goodreads_df["ISBN"].astype(str).str.strip().str.replace('=', '', regex=False).str.replace('"', '', regex=False)
goodreads_df["ISBN13"] = goodreads_df["ISBN13"].astype(str).str.strip().str.replace('=', '', regex=False).str.replace('"', '', regex=False)

In [68]:
goodreads_df.head(20)

,Title,Author,ISBN,ISBN13,Number of Pages,Original Publication Year,Bookshelves,Exclusive Shelf,My Rating,Average Rating,has_page_count
613,For Whom the Bell Tolls,Ernest Hemingway,,,471.0,1940.0,american,read,0,3.99,1
619,The Adventures of Tom Sawyer,Mark Twain,,9780143039563,244.0,1876.0,american,read,0,3.92,1
612,The Fountainhead,Ayn Rand,,,704.0,1943.0,american,read,1,3.89,1
999,To Have and Have Not,Ernest Hemingway,,,176.0,1937.0,american,read,1,3.51,1
230,Hello Beautiful,Ann Napolitano,,,400.0,2023.0,american,read,2,4.13,1
614,Do Androids Dream of Electric Sheep?,Philip K. Dick,,,244.0,1968.0,american,read,2,4.09,1
204,The Vanishing Half,Brit Bennett,0525536299,9780525536291,343.0,2020.0,american,read,3,4.12,1
306,All the Light We Cannot See,Anthony Doerr,1476746583,9781476746586,531.0,2014.0,american,read,3,4.31,1
419,The Collected Stories,Amy Hempel,0743289463,9780743289467,432.0,2006.0,american,read,3,4.25,1
377,Where the Crawdads Sing,Delia Owens,0735219117,9780735219113,384.0,2018.0,american,read,4,4.37,1
423,Fahrenheit 451,Ray Bradbury,,,194.0,1953.0,american,read,4,3.97,1
615,The Catcher in the Rye,J.D. Salinger,0316769177,9780316769174,277.0,1951.0,american,read,4,3.80,1
616,The Call of the Wild,Jack London,,,172.0,1903.0,american,read,5,3.91,1
617,Breakfast at Tiffany’s and Three Stories,Truman Capote,,,142.0,1958.0,american,read,5,3.85,1
620,The Adventures of Huckleberry Finn (Adventures...,Mark Twain,0142437174,9780142437179,327.0,1885.0,american,read,5,3.83,1
136,Tender Is the Night,F. Scott Fitzgerald,,,430.0,1934.0,"american, own",read,4,3.77,1
281,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,0439023483,9780439023481,374.0,2008.0,"american, read-in-german",read,3,4.35,1
552,I'm Glad My Mom Died,Jennette McCurdy,,,320.0,2022.0,auto-biography,read,0,4.44,1
590,Journal 1970-1986,Andrei Tarkovsky,,,NaN,1989.0,auto-biography,read,0,4.34,0
127,Born a Crime: Stories from a South African Chi...,Trevor Noah,0385689225,9780385689229,289.0,2016.0,auto-biography,read,2,4.49,1

In [69]:
goodreads_df['Bookshelves'].isna().sum()

np.int64(0)

In [ ]:
# Clean up tags in 'Bookshelves' column
goodreads_df['Bookshelves'] = goodreads_df['Bookshelves'].str.lower().str.strip()
goodreads_df['Bookshelves'].head(20)

613                    american
619                    american
612                    american
999                    american
230                    american
614                    american
204                    american
306                    american
419                    american
377                    american
423                    american
615                    american
616                    american
617                    american
620                    american
136               american,-own
281    american,-read-in-german
552              auto-biography
590              auto-biography
127              auto-biography
Name: Bookshelves, dtype: object